# Generated by Django 4.0.1 on 2022-02-24 11:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('0', 'Acheminement'), ('1', 'Négociation'), ('2', 'Signé'), ('3', 'Terminé')], default='0', max_length=64)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updating_time', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_client_id', to='crm.client')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_user_id', to='crm.client')),
            ],
        ),
    ]
