# Generated by Django 4.0.1 on 2022-02-24 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='client_id',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
