# Generated by Django 4.0.1 on 2022-02-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_contract_client_id_contract_contract_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
