# Generated by Django 4.0.1 on 2022-02-24 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0005_alter_contract_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='author',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='manager',
        ),
        migrations.AddField(
            model_name='client',
            name='client_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_client_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_contract_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
