# Generated by Django 4.0.1 on 2022-02-24 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0006_rename_author_contract_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('date_event_start', models.DateTimeField(null=True)),
                ('date_event_end', models.DateTimeField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updating_time', models.DateTimeField(null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_contract_id', to='crm.contract')),
                ('event_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_manager_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
