# Generated by Django 4.0.1 on 2022-02-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', 'Management'), ('1', 'Sales'), ('2', 'Support'), ('3', 'Client')], default='3', max_length=64),
        ),
        migrations.DeleteModel(
            name='CustomPermission',
        ),
    ]
