# Generated by Django 4.0.1 on 2022-02-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', 'Management'), ('1', 'Sale'), ('2', 'Support'), ('3', 'Client')], default='0', max_length=64),
        ),
    ]
