# Generated by Django 4.0.1 on 2022-02-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_delete_custompermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('delete_user', 'delete_user'), ('client_Edit_and_delete', 'client_Edit_and_delete'), ('Equipe de gestion', 'Equipe de gestion'), ('Equipe de vente', 'Equipe de vente'), ('Equipe de support', 'Equipe de support')], default='3', max_length=64),
        ),
    ]
