# Generated by Django 4.0.1 on 2022-03-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_managementgroupname_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managementgroupname',
            options={'verbose_name_plural': 'Management group name'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Equipe de support', 'Equipe de support'), ('Equipe de gestion', 'Equipe de gestion'), ('Equipe de vente', 'Equipe de vente')], max_length=64),
        ),
    ]
