# Generated by Django 4.0.1 on 2022-03-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_managementgroupname_options_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Equipe de support', 'Equipe de support'), ('Equipe de vente', 'Equipe de vente'), ('Equipe de gestion', 'Equipe de gestion')], max_length=64),
        ),
    ]
