# Generated by Django 4.0.1 on 2022-02-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_client_management_sales_support_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
        migrations.DeleteModel(
            name='management',
        ),
        migrations.DeleteModel(
            name='sales',
        ),
        migrations.DeleteModel(
            name='support',
        ),
    ]
